name: transforming-transformers
version: 0.1.0
github: "jkachmar/transforming-transformers"
license: MPL-2.0
author: "Joe Kachmar"
copyright: "2019 Joe Kachmar"

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - KindSignatures
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - TypeApplications

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - generic-lens
  - lens
  - mtl
  - text
  - transformers

library:
  source-dirs: library

executables:
  demo:
    main: Main.hs
    source-dirs: executables
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - transforming-transformers

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - transforming-transformers
